-- MySQL Script generated by MySQL Workbench
-- Tue Jan 17 20:25:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema I_City
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema I_City
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `I_City` DEFAULT CHARACTER SET utf8 ;
USE `I_City` ;

-- -----------------------------------------------------
-- Table `I_City`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `I_City`.`user` (
  `u_id` VARCHAR(50) COMMENT '唯一标识用户的编号' NOT NULL,
  `u_name` VARCHAR(50) NULL COMMENT '用户名',
  `u_nickname` VARCHAR(50) NULL COMMENT '昵称',
  `u_password` VARCHAR(50) NULL COMMENT '密码',
  `register_date` VARCHAR(50) NULL COMMENT '注册日期',
  `u_remark` VARCHAR(100) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `I_City`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `I_City`.`user_info` (
  `u_id` VARCHAR(50) COMMENT '唯一标识用户的编号',
  `true_name` VARCHAR(50) NULL COMMENT '用户真实姓名',
  `u_sex` VARCHAR(50) NULL COMMENT '性别',
  `birthday` VARCHAR(50) NULL COMMENT '生日',
  `age` INT NULL COMMENT '年龄',
  `qq` VARCHAR(13) NULL COMMENT 'qq号码',
  `tel` VARCHAR(50) NULL COMMENT '电话',
  `email` VARCHAR(50) NULL COMMENT '邮箱',
  `introduce` VARCHAR(100) NULL COMMENT '用户简介',
  `declaration` VARCHAR(100) NULL COMMENT '个人宣言',
  `profession` VARCHAR(50) NULL COMMENT '职业',
  `img_url` VARCHAR(50) NULL COMMENT '头像地址',
  `user_info_remark` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户个人信息备注',
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC),
  CONSTRAINT `u_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `I_City`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `I_City`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `I_City`.`photo` (
  `p_id` INT COMMENT '唯一标识图片的编号' NOT NULL,
  `u_id` VARCHAR(45) NULL COMMENT '用户id编号',
  `p_name` VARCHAR(45) NULL COMMENT '图片名称',
  `photo_url` VARCHAR(45) NULL COMMENT '图片地址',
  `up_time` VARCHAR(45) NULL COMMENT '上传图片名称',
  `p_remark` VARCHAR(45) NULL DEFAULT NULL COMMENT '图片备注',
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `I_City`.`moments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `I_City`.`moments` (
  `m_id` VARCHAR(50) NOT NULL COMMENT '唯一动态标志符' NOT NULL,
  `u_id` VARCHAR(50) NULL COMMENT '唯一用户标识符',
  `img_urls` VARCHAR(50) NULL COMMENT '动态图片存放位置',
  `text_content` VARCHAR(100) NULL COMMENT '动态内容',
  `m_up_time` VARCHAR(50) NULL COMMENT '动态上传时间',
  `m_del_time` VARCHAR(50) NULL COMMENT '动态删除时间',
  `m_location` VARCHAR(50) NULL COMMENT '发动态的地点',
  PRIMARY KEY (`m_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
